version: '3.6'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=sales_cart
      - POSTGRES_USER=cart
      - POSTGRES_PASSWORD=Abrir.01
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=sales_cart
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Abrir.01
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql